/**
 * Lunar landing sites (selenographic lat/lon, Mean Earth / Polar Axis).
 * Lon east-positive; 0° ≈ near-side center (Sinus Medii).
 * Apollo / Luna / Lunokhod / Surveyor: LROC anthropogenic coordinates (Wagner et al. 2017).
 * Others: published mission / agency landing solutions (within ~0.01–0.1°).
 *
 * famous: true → gold in "Famous" and every broader tier.
 * kind defaults to "landing"; impact / failed-attempt sites appear only in "All".
 */
export const MISSION_SITES = [
  // —— Famous tier (curated firsts & stories) ——
  {
    id: "apollo11",
    name: "Apollo 11",
    year: 1969,
    agency: "USA · NASA",
    lat: 0.67416,
    lon: 23.47314,
    famous: true,
    blurb: "First crewed landing. Armstrong and Aldrin walked in the Sea of Tranquility.",
  },
  {
    id: "apollo12",
    name: "Apollo 12",
    year: 1969,
    agency: "USA · NASA",
    lat: -3.0128,
    lon: -23.4219,
    famous: true,
    blurb: "Precision landing near Surveyor 3 in Oceanus Procellarum.",
  },
  {
    id: "apollo14",
    name: "Apollo 14",
    year: 1971,
    agency: "USA · NASA",
    lat: -3.64589,
    lon: -17.47194,
    famous: true,
    blurb: "Fra Mauro highlands. Shepard hit a golf ball on the lunar surface.",
  },
  {
    id: "apollo15",
    name: "Apollo 15",
    year: 1971,
    agency: "USA · NASA",
    lat: 26.13239,
    lon: 3.6333,
    famous: true,
    blurb: "Hadley–Apennine. First Lunar Roving Vehicle and deep drill core.",
  },
  {
    id: "apollo16",
    name: "Apollo 16",
    year: 1972,
    agency: "USA · NASA",
    lat: -8.9734,
    lon: 15.5011,
    famous: true,
    blurb: "Descartes highlands — explored lunar highlands geology with the rover.",
  },
  {
    id: "apollo17",
    name: "Apollo 17",
    year: 1972,
    agency: "USA · NASA",
    lat: 20.1911,
    lon: 30.7723,
    famous: true,
    blurb: "Taurus–Littrow. Last crewed landing; geologist Schmitt walked the Moon.",
  },
  {
    id: "surveyor3",
    name: "Surveyor 3",
    year: 1967,
    agency: "USA · NASA",
    lat: -3.0162,
    lon: -23.418,
    famous: true,
    blurb: "Soft lander later visited by Apollo 12; parts returned to Earth.",
  },
  {
    id: "lunokhod1",
    name: "Lunokhod 1",
    year: 1970,
    agency: "USSR",
    lat: 38.315,
    lon: -35.0081,
    famous: true,
    blurb: "First successful planetary rover — drove across Mare Imbrium.",
  },
  {
    id: "luna9",
    name: "Luna 9",
    year: 1966,
    agency: "USSR",
    lat: 7.08,
    lon: -64.37,
    famous: true,
    blurb: "First soft landing on another world; returned panoramic images.",
  },
  {
    id: "luna16",
    name: "Luna 16",
    year: 1970,
    agency: "USSR",
    lat: -0.5137,
    lon: 56.3638,
    famous: true,
    blurb: "First robotic sample return — brought Mare Fecunditatis soil to Earth.",
  },
  {
    id: "change4",
    name: "Chang’e 4",
    year: 2019,
    agency: "China · CNSA",
    lat: -45.444,
    lon: 177.599,
    famous: true,
    blurb: "First landing on the far side — Von Kármán crater, with the Yutu-2 rover.",
  },
  {
    id: "change5",
    name: "Chang’e 5",
    year: 2020,
    agency: "China · CNSA",
    lat: 43.058,
    lon: -51.916,
    famous: true,
    blurb: "Returned young basalt samples from Oceanus Procellarum.",
  },
  {
    id: "chandrayaan3",
    name: "Chandrayaan-3",
    year: 2023,
    agency: "India · ISRO",
    lat: -69.373,
    lon: 32.319,
    famous: true,
    blurb: "First soft landing near the lunar south pole (Vikram lander / Pragyan rover).",
  },
  {
    id: "slimin1",
    name: "SLIM",
    year: 2024,
    agency: "Japan · JAXA",
    lat: -13.316,
    lon: 25.251,
    famous: true,
    blurb: "“Moon Sniper” precision landing in Mare Nectaris highlands.",
  },
  {
    id: "odyssey",
    name: "Odysseus (IM-1)",
    year: 2024,
    agency: "USA · Intuitive Machines",
    lat: -80.13,
    lon: 1.44,
    famous: true,
    blurb: "First US commercial soft lander; tipped near the south polar region.",
  },

  // —— Landings tier (every other successful landing) ——
  {
    id: "luna13",
    name: "Luna 13",
    year: 1966,
    agency: "USSR",
    lat: 18.87,
    lon: -62.05,
    blurb: "Second Soviet soft lander — tested soil density in Oceanus Procellarum.",
  },
  {
    id: "luna20",
    name: "Luna 20",
    year: 1972,
    agency: "USSR",
    lat: 3.7863,
    lon: 56.6242,
    blurb: "Robotic sample return from the Apollonius highlands.",
  },
  {
    id: "luna21",
    name: "Luna 21 · Lunokhod 2",
    year: 1973,
    agency: "USSR",
    lat: 25.9994,
    lon: 30.4076,
    blurb: "Delivered Lunokhod 2, which drove a record ~39 km across Le Monnier crater.",
  },
  {
    id: "luna23",
    name: "Luna 23",
    year: 1974,
    agency: "USSR",
    lat: 12.6667,
    lon: 62.1511,
    blurb: "Landed in Mare Crisium but was damaged on touchdown; no samples returned.",
  },
  {
    id: "luna24",
    name: "Luna 24",
    year: 1976,
    agency: "USSR",
    lat: 12.7142,
    lon: 62.2129,
    blurb: "Last Soviet Moon mission — returned Mare Crisium core samples to Earth.",
  },
  {
    id: "surveyor1",
    name: "Surveyor 1",
    year: 1966,
    agency: "USA · NASA",
    lat: -2.474,
    lon: -43.339,
    blurb: "First US soft landing — proved landings were possible for Apollo.",
  },
  {
    id: "surveyor5",
    name: "Surveyor 5",
    year: 1967,
    agency: "USA · NASA",
    lat: 1.41,
    lon: 23.18,
    blurb: "First chemical analysis of lunar soil, in Mare Tranquillitatis.",
  },
  {
    id: "surveyor6",
    name: "Surveyor 6",
    year: 1967,
    agency: "USA · NASA",
    lat: 0.49,
    lon: -1.4,
    blurb: "Landed in Sinus Medii and performed the first liftoff from the Moon (a short hop).",
  },
  {
    id: "surveyor7",
    name: "Surveyor 7",
    year: 1968,
    agency: "USA · NASA",
    lat: -40.98,
    lon: -11.51,
    blurb: "Last Surveyor — explored the rugged rim of Tycho crater.",
  },
  {
    id: "change3",
    name: "Chang’e 3",
    year: 2013,
    agency: "China · CNSA",
    lat: 44.1214,
    lon: -19.5117,
    blurb: "First soft landing since 1976 — delivered the Yutu rover to Mare Imbrium.",
  },
  {
    id: "change6",
    name: "Chang’e 6",
    year: 2024,
    agency: "China · CNSA",
    lat: -41.64,
    lon: -153.99,
    blurb: "First far-side sample return, from the Apollo basin.",
  },
  {
    id: "blueghost1",
    name: "Blue Ghost 1",
    year: 2025,
    agency: "USA · Firefly Aerospace",
    lat: 18.56,
    lon: 61.81,
    blurb: "First fully successful commercial landing — worked two weeks in Mare Crisium.",
  },
  {
    id: "athena",
    name: "Athena (IM-2)",
    year: 2025,
    agency: "USA · Intuitive Machines",
    lat: -84.76,
    lon: 29.16,
    blurb: "Landed near Mons Mouton by the south pole but tipped; brief drill demo.",
  },

  // —— All tier (impacts and unsuccessful landing attempts) ——
  {
    id: "luna2",
    name: "Luna 2",
    year: 1959,
    agency: "USSR",
    lat: 29.1,
    lon: 0,
    kind: "impact",
    approximate: true,
    blurb: "First human-made object to reach another world, intentionally impacting near Palus Putredinis.",
  },
  {
    id: "ranger4",
    name: "Ranger 4",
    year: 1962,
    agency: "USA · NASA",
    lat: -15.5,
    lon: -130.7,
    kind: "impact",
    approximate: true,
    blurb: "Communications failed before Ranger 4 became the first US spacecraft to reach the Moon.",
  },
  {
    id: "ranger6",
    name: "Ranger 6",
    year: 1964,
    agency: "USA · NASA",
    lat: 9.3864,
    lon: 21.4806,
    kind: "impact",
    blurb: "Intentional imaging impact; its television system failed before it could return close-up pictures.",
  },
  {
    id: "ranger7",
    name: "Ranger 7",
    year: 1964,
    agency: "USA · NASA",
    lat: -10.634,
    lon: -20.677,
    kind: "impact",
    blurb: "Returned the first successful US close-up lunar images before impacting Mare Cognitum.",
  },
  {
    id: "ranger8",
    name: "Ranger 8",
    year: 1965,
    agency: "USA · NASA",
    lat: 2.6376,
    lon: 24.7881,
    kind: "impact",
    blurb: "Sent back more than 7,000 images before its planned impact in Mare Tranquillitatis.",
  },
  {
    id: "ranger9",
    name: "Ranger 9",
    year: 1965,
    agency: "USA · NASA",
    lat: -12.8281,
    lon: -2.3884,
    kind: "impact",
    blurb: "Its live television images carried viewers down toward Alphonsus crater before impact.",
  },
  {
    id: "luna5",
    name: "Luna 5",
    year: 1965,
    agency: "USSR",
    lat: -31,
    lon: 8,
    kind: "attempt",
    approximate: true,
    blurb: "A failed soft-landing attempt; loss of attitude control led to an impact in Mare Nubium.",
  },
  {
    id: "luna7",
    name: "Luna 7",
    year: 1965,
    agency: "USSR",
    lat: 9,
    lon: -40,
    kind: "attempt",
    approximate: true,
    blurb: "A landing attempt that lost attitude control during descent and impacted Oceanus Procellarum.",
  },
  {
    id: "luna8",
    name: "Luna 8",
    year: 1965,
    agency: "USSR",
    lat: 9.13,
    lon: -63.3,
    kind: "attempt",
    approximate: true,
    blurb: "Its landing sequence began correctly, but an airbag deployment upset the craft before impact.",
  },
  {
    id: "surveyor2",
    name: "Surveyor 2",
    year: 1966,
    agency: "USA · NASA",
    lat: 5.5,
    lon: -12,
    kind: "attempt",
    approximate: true,
    blurb: "A failed landing attempt after one vernier engine did not ignite, sending the craft into a tumble.",
  },
  {
    id: "surveyor4",
    name: "Surveyor 4",
    year: 1967,
    agency: "USA · NASA",
    lat: 0.4,
    lon: -1.33,
    kind: "attempt",
    approximate: true,
    blurb: "Contact ended about two and a half minutes before its planned touchdown in Sinus Medii.",
  },
  {
    id: "luna15",
    name: "Luna 15",
    year: 1969,
    agency: "USSR",
    lat: 17,
    lon: 60,
    kind: "attempt",
    approximate: true,
    blurb: "An attempted robotic sample return that crashed while Apollo 11 astronauts were still on the Moon.",
  },
  {
    id: "apollo13-sivb",
    name: "Apollo 13 S-IVB",
    year: 1970,
    agency: "USA · NASA",
    lat: -2.555,
    lon: -27.8875,
    kind: "impact",
    blurb: "The spent Saturn V third stage was deliberately impacted to calibrate Apollo seismometers.",
  },
  {
    id: "apollo14-sivb",
    name: "Apollo 14 S-IVB",
    year: 1971,
    agency: "USA · NASA",
    lat: -8.181,
    lon: -26.0305,
    kind: "impact",
    blurb: "A planned rocket-stage impact used as a known seismic source for instruments on the Moon.",
  },
  {
    id: "luna18",
    name: "Luna 18",
    year: 1971,
    agency: "USSR",
    lat: 3.76,
    lon: 56.655,
    kind: "attempt",
    approximate: true,
    blurb: "A sample-return attempt that crashed in rugged terrain near Mare Fecunditatis.",
  },
  {
    id: "apollo15-sivb",
    name: "Apollo 15 S-IVB",
    year: 1971,
    agency: "USA · NASA",
    lat: -1.2897,
    lon: -11.8245,
    kind: "impact",
    blurb: "A deliberate Saturn V third-stage impact recorded by the Apollo seismic network.",
  },
  {
    id: "apollo16-sivb",
    name: "Apollo 16 S-IVB",
    year: 1972,
    agency: "USA · NASA",
    lat: 1.921,
    lon: -24.623,
    kind: "impact",
    blurb: "A deliberate rocket-stage impact whose measured crater helped calibrate lunar seismic data.",
  },
  {
    id: "apollo17-sivb",
    name: "Apollo 17 S-IVB",
    year: 1972,
    agency: "USA · NASA",
    lat: -4.1681,
    lon: -12.3307,
    kind: "impact",
    blurb: "The final Apollo Saturn V third stage intentionally struck the Moon as a seismic experiment.",
  },
  {
    id: "lunar-prospector",
    name: "Lunar Prospector",
    year: 1999,
    agency: "USA · NASA",
    lat: -87.7,
    lon: 42.1,
    kind: "impact",
    approximate: true,
    blurb: "The orbiter ended with a controlled impact near the south pole in a search for water vapor.",
  },
  {
    id: "smart1",
    name: "SMART-1",
    year: 2006,
    agency: "Europe · ESA",
    lat: -34.262,
    lon: -46.193,
    kind: "impact",
    blurb: "Europe’s first lunar probe ended in a planned, grazing impact after testing solar-electric propulsion.",
  },
  {
    id: "chandrayaan1-mip",
    name: "Chandrayaan-1 MIP",
    year: 2008,
    agency: "India · ISRO",
    lat: -89.76,
    lon: -39.4,
    kind: "impact",
    approximate: true,
    blurb: "India’s Moon Impact Probe descended near Shackleton crater and helped confirm lunar water.",
  },
  {
    id: "change1",
    name: "Chang’e 1",
    year: 2009,
    agency: "China · CNSA",
    lat: -1.5,
    lon: 52.36,
    kind: "impact",
    approximate: true,
    blurb: "China’s first lunar orbiter completed its mapping mission with a controlled impact.",
  },
  {
    id: "kaguya",
    name: "Kaguya (SELENE)",
    year: 2009,
    agency: "Japan · JAXA",
    lat: -65.5,
    lon: 80.4,
    kind: "impact",
    approximate: true,
    blurb: "Japan’s Kaguya orbiter ended its successful mission with a controlled impact near the southeast limb.",
  },
  {
    id: "lcross-centaur",
    name: "LCROSS Centaur",
    year: 2009,
    agency: "USA · NASA",
    lat: -84.6796,
    lon: -48.7093,
    kind: "impact",
    blurb: "A rocket stage deliberately struck shadowed Cabeus crater, excavating a plume containing water.",
  },
  {
    id: "lcross-ssc",
    name: "LCROSS Shepherd",
    year: 2009,
    agency: "USA · NASA",
    lat: -84.719,
    lon: -49.61,
    kind: "impact",
    blurb: "The shepherding spacecraft sampled the Centaur’s plume, transmitted its findings, then impacted nearby.",
  },
  {
    id: "grail-a",
    name: "GRAIL-A · Ebb",
    year: 2012,
    agency: "USA · NASA",
    lat: 75.6088,
    lon: -26.594,
    kind: "impact",
    blurb: "One of twin gravity-mapping probes deliberately deorbited into a mountain near the north pole.",
  },
  {
    id: "grail-b",
    name: "GRAIL-B · Flow",
    year: 2012,
    agency: "USA · NASA",
    lat: 75.6508,
    lon: -26.8341,
    kind: "impact",
    blurb: "The second GRAIL probe followed its twin into a controlled impact about 30 seconds later.",
  },
  {
    id: "ladee",
    name: "LADEE",
    year: 2014,
    agency: "USA · NASA",
    lat: 11.8494,
    lon: -93.2494,
    kind: "impact",
    blurb: "After studying the Moon’s tenuous atmosphere and dust, LADEE was deliberately deorbited on the far side.",
  },
  {
    id: "beresheet",
    name: "Beresheet",
    year: 2019,
    agency: "Israel · SpaceIL",
    lat: 32.5956,
    lon: 19.3496,
    kind: "attempt",
    blurb: "A privately funded landing attempt that reached Mare Serenitatis but crashed after an engine shutdown.",
  },
  {
    id: "vikram-2019",
    name: "Vikram · Chandrayaan-2",
    year: 2019,
    agency: "India · ISRO",
    lat: -70.881,
    lon: 22.784,
    kind: "attempt",
    blurb: "The Vikram lander deviated during descent and impacted near the south polar region.",
  },
  {
    id: "hakuto-r-m1",
    name: "HAKUTO-R Mission 1",
    year: 2023,
    agency: "Japan · ispace",
    lat: 47.581,
    lon: 44.094,
    kind: "attempt",
    blurb: "A commercial lander lost altitude data and impacted near Atlas crater during its final descent.",
  },
  {
    id: "luna25",
    name: "Luna 25",
    year: 2023,
    agency: "Russia · Roscosmos",
    lat: -57.865,
    lon: 61.36,
    kind: "attempt",
    blurb: "An overlong engine burn put the lander on an impact trajectory before its south-polar landing attempt.",
  },
  {
    id: "hakuto-r-m2",
    name: "RESILIENCE · HAKUTO-R M2",
    year: 2025,
    agency: "Japan · ispace",
    lat: 60.5,
    lon: -4.6,
    kind: "attempt",
    approximate: true,
    blurb: "The second HAKUTO-R lander lost accurate altitude sensing and made a hard landing in Mare Frigoris.",
  },
  {
    id: "f9-2025-010d",
    name: "Falcon 9 upper stage (2025-010D)",
    year: 2026,
    agency: "USA · SpaceX",
    lat: 19.461,
    lon: -93.293,
    kind: "impact",
    approximate: true,
    pinColor: 0xe53e3e,
    blurb: "Spent Falcon 9 second stage (COSPAR 2025-010D) predicted to impact near Einstein crater on the western limb, ~06:35 UTC Aug 5 2026 (~02:35 EDT). Trajectory from Bill Gray / Project Pluto.",
  },
];
